# Based on https://github.com/malept/rusty_blank/blob/master/.travis.yml
# and https://github.com/d-unseductable/ruru/blob/master/.travis.yml

language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

before_install:
- |
  rvm install "$BUILD_RUBY_VERSION"
  rvm use "$BUILD_RUBY_VERSION"
  ruby --version
  ruby -e 'require "pp"; pp RbConfig::CONFIG'

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- |
  travis-cargo build &&
  travis-cargo test

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  matrix:
    - BUILD_RUBY_VERSION: 2.2.5
    - BUILD_RUBY_VERSION: 2.3.1
    - BUILD_RUBY_VERSION: 2.4.0
