[package]
name = "ruby-sys"
version = "0.1.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>",
           "Dmitry Gritsay <unseductable@gmail.com>"]

build = "build.rs"
links = "ruby"

[dependencies]
libc = "0.2.10"
